name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: '[Bug]: '
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible to help us understand and fix the issue.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have tested with the latest version of react-history-state
          required: true
        - label: I have read the documentation
          required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of react-history-state are you using?
      placeholder: 'e.g., 1.0.0'
    validations:
      required: true

  - type: input
    id: react-version
    attributes:
      label: React Version
      description: What version of React are you using?
      placeholder: 'e.g., 18.2.0'
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you running in?
      options:
        - Browser
        - Node.js (SSR)
        - React Native
        - Next.js
        - Vite
        - Create React App
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Import useHistoryState from 'react-history-state'
        2. Use the hook with specific options...
        3. Perform action...
        4. See error/unexpected behavior
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Minimal Reproduction Code
      description: Please provide a minimal code sample that reproduces the issue
      render: typescript
      placeholder: |
        import { useHistoryState } from 'react-history-state';

        function MyComponent() {
          const { state, setState, undo, redo } = useHistoryState('initial');
          // Your reproduction code here...
        }

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, console errors, or information about the problem
      placeholder: Any additional information that might help us diagnose the issue...
