name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['enhancement', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea clearly to help us understand and evaluate it.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have checked the documentation to ensure this isn't already possible
          required: true
        - label: This is a feature request, not a bug report
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I considered using... but it doesn't work because...

  - type: textarea
    id: api-design
    attributes:
      label: Proposed API (if applicable)
      description: If this involves new APIs, show what the usage would look like
      render: typescript
      placeholder: |
        // Example usage:
        const { state, setState } = useHistoryState('initial', {
          // new option here
        });

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and why this feature would be beneficial
      placeholder: This would help developers who...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would significantly improve my workflow
        - High - Blocking my current project
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request
      placeholder: Any additional information that might help...
